/** Sidebar + anchor IDs for legal document layouts */

export type LegalTocItem = { id: string; label: string };

export const TERMS_TOC: LegalTocItem[] = [
  { id: 'terms-definitions', label: 'Definitions' },
  { id: 'terms-consent', label: 'Consent' },
  { id: 'terms-site-rules', label: 'Site Rules' },
  { id: 'terms-disclaimer', label: 'Disclaimer' },
  { id: 'terms-your-consent', label: 'Your Consent to These Terms & Conditions' },
  { id: 'terms-changes', label: 'Changes To These Terms & Conditions' },
  { id: 'terms-third-party', label: 'Links to Third-Party or External Websites' },
  { id: 'terms-ip', label: 'Intellectual Property Ownership' },
  { id: 'terms-limited-license', label: 'Our Limited License to You' },
  { id: 'terms-license-to-us', label: 'Your License to Us' },
  { id: 'terms-purchase', label: 'Purchase & Access Terms' },
  { id: 'terms-personal-use', label: 'Personal Use Only & Prohibited Conduct' },
  { id: 'terms-sharing', label: 'Sharing the Site & Its Content' },
  { id: 'terms-no-claims', label: 'No Claims Made Regarding Results' },
  { id: 'terms-no-warranties', label: 'No Warranties, Guarantees, or Representations' },
  { id: 'terms-release', label: 'Your Release of Us' },
  { id: 'terms-errors', label: 'Errors & Omissions' },
  { id: 'terms-refund', label: 'Our Refund Policy' },
  { id: 'terms-arbitration', label: 'Arbitration Clause' },
  { id: 'terms-governing-law', label: 'Consent to Governing Law' },
  { id: 'terms-jurisdiction', label: 'Consent to Jurisdiction' },
  { id: 'terms-service', label: 'Consent to Service' },
  { id: 'terms-payment', label: 'Payment & Purchases' },
  { id: 'terms-liability', label: 'Limitation of Liability' },
  { id: 'terms-indemnification', label: 'Defense & Indemnification' },
  { id: 'terms-termination', label: 'Termination of Your Use' },
  { id: 'terms-entire', label: 'Entire Agreement' },
  { id: 'terms-severability', label: 'Severability' },
  { id: 'terms-contact', label: 'Contact' },
];

export const PRIVACY_TOC: LegalTocItem[] = [
  { id: 'privacy-definitions', label: 'Definitions' },
  { id: 'privacy-company', label: 'Company Statement' },
  { id: 'privacy-collect', label: 'What We Collect' },
  { id: 'privacy-update', label: 'Correcting Your Information' },
  { id: 'privacy-when', label: 'When We Collect Information' },
  { id: 'privacy-use', label: 'How We Use Your Information' },
  { id: 'privacy-share', label: 'Sharing Information' },
  { id: 'privacy-protect', label: 'How We Protect Information' },
  { id: 'privacy-cookies', label: 'Cookies & Pixels' },
  { id: 'privacy-third-links', label: 'Third-Party Links' },
  { id: 'privacy-password', label: 'Password Privacy' },
  { id: 'privacy-google', label: 'Google Ads & Analytics' },
  { id: 'privacy-caloppa', label: 'CalOPPA' },
  { id: 'privacy-coppa', label: 'COPPA' },
  { id: 'privacy-fair', label: 'Fair Information Practices' },
  { id: 'privacy-can-spam', label: 'CAN-SPAM Act' },
  { id: 'privacy-gdpr', label: 'GDPR Rights' },
  { id: 'privacy-contact', label: 'Contacting Us' },
];

export const DISCLAIMERS_TOC: LegalTocItem[] = [
  { id: 'disc-definitions', label: 'Definitions' },
  { id: 'disc-disclaimer', label: 'Disclaimer' },
  { id: 'disc-affiliate', label: 'Affiliate Links/Products' },
  { id: 'disc-sponsored', label: 'Sponsored Posts' },
  { id: 'disc-professional', label: 'Professional Advice' },
  { id: 'disc-warranties', label: 'No Warranties' },
  { id: 'disc-liability', label: 'Disclaimer of Liability' },
  { id: 'disc-testimonials', label: 'Testimonials' },
  { id: 'disc-endorsements', label: 'No Endorsements' },
  { id: 'disc-earnings', label: 'Earnings Disclaimer' },
  { id: 'disc-legal-links', label: 'Privacy Policy + Terms' },
  { id: 'disc-contact', label: 'Contact Us' },
];
